set(USER_NEP_SOURCES_DIR ${LAMMPS_SOURCE_DIR}/USER-NEP)

RegisterStyles(${USER_NEP_SOURCES_DIR})

set(USER_NEP_SOURCES
  ${USER_NEP_SOURCES_DIR}/pair_NEP.cpp
  ${USER_NEP_SOURCES_DIR}/nep.cpp
  ${USER_NEP_SOURCES_DIR}/neighbor_nep.cpp
  ${USER_NEP_SOURCES_DIR}/ewald_nep.cpp
)

set(USER_NEP_HEADERS
  ${USER_NEP_SOURCES_DIR}/pair_NEP.h
  ${USER_NEP_SOURCES_DIR}/nep.h
  ${USER_NEP_SOURCES_DIR}/neighbor_nep.h
  ${USER_NEP_SOURCES_DIR}/ewald_nep.h
  ${USER_NEP_SOURCES_DIR}/dftd3para.h
  ${USER_NEP_SOURCES_DIR}/nep_utilities.h
)

get_property(LAMMPS_HEADERS GLOBAL PROPERTY HEADERS)
list(APPEND LAMMPS_HEADERS ${USER_NEP_HEADERS})
set_property(GLOBAL PROPERTY HEADERS "${LAMMPS_HEADERS}")

get_target_property(LAMMPS_SOURCES lammps SOURCES)
list(APPEND LAMMPS_SOURCES ${USER_NEP_SOURCES})
set_property(TARGET lammps PROPERTY SOURCES "${LAMMPS_SOURCES}")

target_include_directories(lammps PRIVATE ${USER_NEP_SOURCES_DIR})
