#!/bin/sh
#SBATCH --job-name=md0
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --partition=3090,4090

echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"

start=$(date +%s)


module load lammps4matpl/2025.3-d3

# or 
# module load cuda/11.8-share intel/2020
# source /share/app/MATPL/lammps-MatPL/lammps-libtorch-d3-2025.3/build/env.sh

which lmp

mpirun -np 1 lmp -in in.lammps
